schema_version = "1.0.0"

id = "lampochka"
version = "2.5.0"
name = "LAMPOCHKA"
tagline = "Manage all lights and HDRI environments in the scene"
maintainer = "Maksim Kovalev <maksim@example.com>"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Read light presets and HDRI files from disk"
